name: CI/CD for .NET Core API

on:
  push:
    branches:
      - desenvolvimentoBackEnd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./sigmaBack.sln

      - name: Build the application
        run: dotnet build ./sigmaBack.sln --configuration Release

      - name: Run tests
        run: dotnet test ./sigmaBack.sln --configuration Release

      - name: Publish the application
        run: |
          dotnet publish ./sigmaBack.API/sigmaBack.API.csproj --configuration Release --output ./publish/API
          dotnet publish ./sigmaBack.Application/sigmaBack.Application.csproj --configuration Release --output ./publish/Application
          dotnet publish ./sigmaBack.Domain/sigmaBack.Domain.csproj --configuration Release --output ./publish/Domain
          dotnet publish ./sigmaBack.Domain.Test/sigmaBack.Domain.Test.csproj --configuration Release --output ./publish/Domain.Test
          dotnet publish ./sigmaback.Infra.Data/sigmaback.Infra.Data.csproj --configuration Release --output ./publish/Infra.Data
          dotnet publish ./sigmaBack.Infra.IoC/sigmaBack.Infra.IoC.csproj --configuration Release --output ./publish/Infra.IoC

      - name: Build Docker image
        run: docker build -t dockersigmasback:latest -f ./sigmaBack.API/Dockerfile ./

      - name: Verify Docker image
        run: docker images dockersigmasback:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          echo "SERVER_USER: lemuel"
          echo "SERVER_IP: www.portalmantec.com.br"
          
          docker save dockersigmasback:latest -o dockersigmasback.tar
          scp -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i private_key dockersigmasback.tar lemuel@www.portalmantec.com.br:/mnt/volumes/apis/docker_sigma_api/docker_sigmaBack.tar
          ssh -o StrictHostKeyChecking=no -i private_key lemuel@www.portalmantec.com.br "docker rm -f sigmaBack-container || true"
          ssh -o StrictHostKeyChecking=no -i private_key lemuel@www.portalmantec.com.br "docker load < /mnt/volumes/apis/docker_sigma_api/docker_sigmaBack.tar"
          ssh -o StrictHostKeyChecking-no -i private_key lemuel@www.portalmantec.com.br "docker run -d -p 5001:5001 -p 5002:5002 --name sigmaBack-container dockersigmasback:latest"
          rm -f private_key
