name: CI/CD for sigmaBackEnd

on:
  push:
    branches:
      - desenvolvimentoBackEnd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configuração do ambiente para o .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Restaura dependências e compila o projeto
      - name: Restore and Build
        run: |
          dotnet restore sigmaBack.sln
          dotnet build sigmaBack.sln --configuration Release

      # Lista arquivos no diretório atual
      - name: List files
        run: ls -la

      # Faz login no servidor para enviar arquivos necessários para o deploy
      - name: Transfer Files to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Salva a chave privada em um arquivo temporário
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          
          # Define variáveis
          DEPLOY_PATH="/mnt/volumes/apis"
          
          # Envia o código e o Dockerfile para o servidor
          scp -o StrictHostKeyChecking=no -i private_key ./Dockerfile $SERVER_USER@$SERVER_IP:$DEPLOY_PATH/
          scp -o StrictHostKeyChecking=no -i private_key -r ./* $SERVER_USER@$SERVER_IP:$DEPLOY_PATH/

          # Remove o arquivo temporário da chave privada
          rm -f private_key

      # Faz login no servidor para construir e implantar a imagem Docker
      - name: Deploy Docker Image to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Salva a chave privada em um arquivo temporário
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          
          # Define variáveis
          CONTAINER_NAME="sigma-backend"
          IMAGE_NAME="sigma-backend:latest"
          DEPLOY_PATH="/mnt/volumes/apis"
          DOCKERFILE_PATH="$DEPLOY_PATH/Dockerfile"
          
          # Conecta ao servidor e realiza o deploy
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << EOF
            # Define variáveis no servidor
            CONTAINER_NAME="sigma-backend"
            IMAGE_NAME="sigma-backend:latest"
            DEPLOY_PATH="/mnt/volumes/apis"
            DOCKERFILE_PATH="$DEPLOY_PATH/Dockerfile"
            
            # Lista arquivos no servidor para verificar a transferência
            ls -la $DEPLOY_PATH
            
            # Remove containers antigos, se existirem
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            
            # Remove imagens antigas, se existirem
            docker rmi $IMAGE_NAME || true
            
            # Constrói a nova imagem
            docker build -t $IMAGE_NAME -f $DOCKERFILE_PATH $DEPLOY_PATH
            
            # Roda o novo container e mapeia para o diretório desejado
            docker run -d --name $CONTAINER_NAME -p 5001:5001 -v $DEPLOY_PATH:/app $IMAGE_NAME
          
          # Remove o arquivo temporário da chave privada
          rm -f private_key
