name: CI/CD for .NET Core API

on:
  push:
    branches:
      - main
      - desenvolvimentoBackEnd
  pull_request:
    branches:
      - main
      - desenvolvimentoBackEnd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build Docker image
        run: docker build -t dockersigmasback:latest -f ./sigmaBack.API/Dockerfile ./

      - name: Save Docker image to a tar file
        run: docker save dockersigmasback:latest -o dockersigmasback.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: dockersigmasback-image
          path: dockersigmasback.tar

      - name: Run tests
        run: dotnet test ./sigmaBack.sln --configuration Release

      - name: Publish .NET projects
        run: |
          dotnet publish ./sigmaBack.API/sigmaBack.API.csproj --configuration Release --output ./publish/API
          dotnet publish ./sigmaBack.Application/sigmaBack.Application.csproj --configuration Release --output ./publish/Application
          dotnet publish ./sigmaBack.Domain/sigmaBack.Domain.csproj --configuration Release --output ./publish/Domain
          dotnet publish ./sigmaBack.Domain.Test/sigmaBack.Domain.Test.csproj --configuration Release --output ./publish/Domain.Test

      - name: Upload published artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-artifacts
          path: ./publish/**
